#!/usr/bin/env bash
# Displays numbers from 1 to 20 and:
#
#   - Displays 4 and then bad luck from China
#   - Displays 9 and then bad luck from Japan
#   - Displays 17 and then bad luck
i=1

while [ $i -le "20" ]
do
    case $i in
        4)
            echo $i
            echo "bad luck from China"
            ;;
        9)
            echo $i
            echo "bad luck from Japan"
            ;;
        17)
            echo $i
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac

    (("i += 1"))
done
